#!/usr/bin/env bash
#####################################################################
# Author    : Erik Dubois
# Website   : https://kiroproject.be
#####################################################################
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
# Purpose:
#   Generate a colour palette from the current wallpaper with pywal and
#   fan it out to the whole Kiro wayfire desktop: waybar (colors.css),
#   mako (notification colours), and wayfire.ini (window borders +
#   workspace/cube/expo backgrounds). Then live-reload each surface.
# Why:
#   This is the edition's theming engine — one wallpaper drives every
#   colour. Run at login from wayfire's [autostart], or by hand with a
#   wallpaper path to re-theme: set-theme.sh ~/Pictures/some.jpg
#####################################################################

set -euo pipefail

WALLPAPER="${1:-$HOME/.config/wayfire/bg/kiro.jpg}"
CACHE="$HOME/.cache/wal/colors.sh"
WAYBAR_COLORS="$HOME/.config/waybar/colors.css"
MAKO_CONFIG="$HOME/.config/mako/config"
WAYFIRE_INI="$HOME/.config/wayfire.ini"

command -v wal >/dev/null 2>&1 || { echo "pywal (wal) not installed — skipping theme"; exit 0; }
[ -f "$WALLPAPER" ] || { echo "Wallpaper not found: $WALLPAPER"; exit 0; }

# Generate the palette. -n: do not set the wallpaper (swaybg owns that). -q: quiet.
wal -i "$WALLPAPER" -n -q

# shellcheck source=/dev/null
source "$CACHE"   # exports $background $foreground $cursor $color0 … $color15

# #rrggbb → "r g b 1.0" (wayfire's float-RGBA colour format).
hex2float() {
    local hex="${1#\#}"
    awk -v r="$((16#${hex:0:2}))" -v g="$((16#${hex:2:2}))" -v b="$((16#${hex:4:2}))" \
        'BEGIN { printf "%.3f %.3f %.3f", r/255, g/255, b/255 }'
}

# ── waybar — regenerate colors.css, then signal waybar to reload ──────────────
cat > "$WAYBAR_COLORS" <<EOF
/* Generated by set-theme.sh (pywal) from ${WALLPAPER##*/}. */
@define-color bg      ${background};
@define-color fg      ${foreground};
@define-color muted   ${color8};
@define-color accent  ${color4};
@define-color accent2 ${color5};
@define-color info    ${color6};
@define-color good    ${color2};
@define-color warn    ${color3};
@define-color crit    ${color1};
EOF

# ── mako — rewrite the colour lines, then reload ──────────────────────────────
if [ -f "$MAKO_CONFIG" ]; then
    sed -i \
        -e "s|^background-color=.*|background-color=${background}|" \
        -e "s|^text-color=.*|text-color=${foreground}|" \
        -e "s|^border-color=.*|border-color=${color4}|" \
        "$MAKO_CONFIG"
fi

# ── wayfire.ini — borders + workspace/cube/expo backgrounds (auto-reloads) ────
if [ -f "$WAYFIRE_INI" ]; then
    accent_f="$(hex2float "$color4")"
    muted_f="$(hex2float "$color8")"
    bg_f="$(hex2float "$background")"
    sed -i \
        -e "s|^active_color = .*|active_color = ${accent_f} 1.0|" \
        -e "s|^inactive_color = .*|inactive_color = ${muted_f} 0.667|" \
        -e "s|^background_color = .*|background_color = ${bg_f} 1.0|" \
        -e "s|^background = .*|background = ${bg_f} 1.0|" \
        "$WAYFIRE_INI"
fi

# ── Reload the live surfaces ──────────────────────────────────────────────────
pkill -SIGUSR2 waybar 2>/dev/null || true   # waybar reloads its CSS on SIGUSR2
makoctl reload 2>/dev/null || true
# wayfire watches wayfire.ini and reloads it automatically on save.

echo "Theme applied from ${WALLPAPER##*/}"
